# Generated by Django 4.2.16 on 2026-06-24 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='démarré le')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='terminé le')),
                ('total_scanned', models.PositiveIntegerField(default=0, verbose_name='total scanné')),
                ('total_valid', models.PositiveIntegerField(default=0, verbose_name='total valides')),
                ('total_rejected', models.PositiveIntegerField(default=0, verbose_name='total rejetés')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to=settings.AUTH_USER_MODEL, verbose_name='agent scanner')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'session de scan',
                'verbose_name_plural': 'sessions de scan',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data_received', models.CharField(help_text='Données brutes scannées', max_length=500, verbose_name='données QR reçues')),
                ('result', models.CharField(choices=[('valid', 'Valide ✅'), ('already_used', 'Déjà utilisé ❌'), ('invalid_qr', 'QR invalide ⛔'), ('wrong_event', 'Mauvais événement ⚠️'), ('ticket_void', 'Ticket annulé 🚫'), ('not_found', 'Ticket introuvable 🔍')], max_length=20, verbose_name='résultat')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='scanné le')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scanner.scansession', verbose_name='session')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='tickets.ticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'log de scan',
                'verbose_name_plural': 'logs de scan',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
