# Generated by Django 4.2.30 on 2026-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='client_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text="Identifiant généré côté client (navigateur) pour un scan. Permet la détection d'idempotence lors des syncs offline : si un client_uuid est déjà traité pour la même session, on renvoie le résultat original au lieu de recréer un scan. NULL = scan online direct (pas de queue).", null=True, verbose_name='identifiant client'),
        ),
    ]
