# Generated by Django 4.2.30 on 2026-09-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventday_tickettype_event_days_and_more'),
        ('scanner', '0002_scanlog_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='event_day',
            field=models.ForeignKey(blank=True, help_text='Jour concerné par ce scan (multi-jours uniquement). NULL pour les billets legacy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='events.eventday', verbose_name="jour d'événement"),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['event_day', 'result'], name='scanner_sca_event_d_610c5f_idx'),
        ),
    ]
