# Generated by Django 4.2.30 on 2026-10-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_freeticketcode'),
        ('scanner', '0003_scanlog_event_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='guest_ticket',
            field=models.ForeignKey(blank=True, help_text="Rempli uniquement pour les GuestTicket (achat sans compte). Vague 4 — permet de tracer 'déjà scanné ce jour' sur les billets multi-jours invités.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='tickets.guestticket', verbose_name='ticket invité'),
        ),
    ]
