# Generated by Django 4.2.16 on 2026-06-23 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='bi-calendar-event', help_text='Classe Bootstrap Icons ex: bi-music-note-beamed', max_length=50, verbose_name='icône Bootstrap')),
                ('color', models.CharField(default='#1B7A3E', help_text='Code hexadécimal ex: #F47920', max_length=7, verbose_name='couleur')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant public sécurisé', unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Généré automatiquement depuis le titre', max_length=220, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('subtitle', models.CharField(blank=True, help_text='Accroche courte affichée sous le titre', max_length=300, verbose_name='sous-titre')),
                ('description', models.TextField(verbose_name='description complète')),
                ('short_description', models.TextField(blank=True, help_text="Résumé pour les cartes d'aperçu (max 500 car.)", max_length=500, verbose_name='description courte')),
                ('tags', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=300, verbose_name='tags')),
                ('start_date', models.DateTimeField(verbose_name='date de début')),
                ('end_date', models.DateTimeField(verbose_name='date de fin')),
                ('doors_open', models.TimeField(blank=True, help_text="Heure d'ouverture avant l'événement", null=True, verbose_name='ouverture des portes')),
                ('sale_start', models.DateTimeField(blank=True, help_text='Laisser vide pour démarrer immédiatement à la publication', null=True, verbose_name='début des ventes')),
                ('sale_end', models.DateTimeField(blank=True, help_text='Laisser vide pour fermer à la date de début', null=True, verbose_name='fin des ventes')),
                ('event_type', models.CharField(choices=[('physical', 'Présentiel'), ('online', 'En ligne'), ('hybrid', 'Hybride')], default='physical', max_length=20, verbose_name="type d'événement")),
                ('venue_name', models.CharField(blank=True, help_text='Ex: Palais de la Culture, Sofitel Abidjan...', max_length=200, verbose_name='nom du lieu')),
                ('venue_address', models.TextField(blank=True, verbose_name='adresse complète')),
                ('venue_city', models.CharField(default='Abidjan', max_length=100, verbose_name='ville')),
                ('venue_country', models.CharField(default="Côte d'Ivoire", max_length=100, verbose_name='pays')),
                ('venue_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('venue_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('online_link', models.URLField(blank=True, help_text='URL du stream ou de la conférence en ligne', verbose_name='lien en ligne')),
                ('cover_image', models.ImageField(blank=True, help_text='Taille recommandée : 1200×600px', null=True, upload_to='events/covers/%Y/%m/', verbose_name='image de couverture')),
                ('thumbnail', models.ImageField(blank=True, help_text='Taille recommandée : 400×400px', null=True, upload_to='events/thumbnails/%Y/%m/', verbose_name='miniature')),
                ('video_url', models.URLField(blank=True, help_text='YouTube ou Vimeo', verbose_name='URL vidéo de présentation')),
                ('is_free', models.BooleanField(default=False, verbose_name='événement gratuit')),
                ('min_price', models.DecimalField(decimal_places=0, default=0, help_text='Calculé automatiquement depuis les types de tickets', max_digits=10, verbose_name='prix minimum')),
                ('total_capacity', models.PositiveIntegerField(default=0, help_text='0 = illimité', verbose_name='capacité totale')),
                ('tickets_sold', models.PositiveIntegerField(default=0, editable=False, verbose_name='tickets vendus')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('cancelled', 'Annulé'), ('completed', 'Terminé'), ('postponed', 'Reporté')], default='draft', max_length=20, verbose_name='statut')),
                ('is_featured', models.BooleanField(default=False, help_text="Affiché en priorité sur la page d'accueil", verbose_name='mis en avant')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='inscription sur approbation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category', verbose_name='catégorie')),
                ('organizer', models.ForeignKey(limit_choices_to={'role': 'organizer'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='organisateur')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: VIP, Standard, Étudiant, Early Bird', max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=0, help_text='0 pour gratuit', max_digits=10, verbose_name='prix (FCFA)')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='0 = illimité', verbose_name='quantité disponible')),
                ('quantity_sold', models.PositiveIntegerField(default=0, editable=False, verbose_name='quantité vendue')),
                ('max_per_order', models.PositiveIntegerField(default=10, verbose_name='maximum par commande')),
                ('sale_start', models.DateTimeField(blank=True, null=True, verbose_name='début vente')),
                ('sale_end', models.DateTimeField(blank=True, null=True, verbose_name='fin vente')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="ordre d'affichage")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': 'type de ticket',
                'verbose_name_plural': 'types de tickets',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['slug'], name='events_even_slug_30eb0f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_date'], name='events_even_status_dfba18_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'status'], name='events_even_organiz_954d89_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', 'status'], name='events_even_is_feat_ff8c54_idx'),
        ),
    ]
