# Generated by Django 4.2.16 on 2026-06-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commission_negotiated',
            field=models.BooleanField(default=False, help_text="True si l'admin a défini un taux personnalisé", verbose_name='commission négociée'),
        ),
        migrations.AddField(
            model_name='event',
            name='commission_note',
            field=models.TextField(blank=True, help_text='Raison de la commission personnalisée', verbose_name='note de commission'),
        ),
        migrations.AddField(
            model_name='event',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text="Pourcentage prélevé sur l'organisateur. Ex: 8.00 = 8%", max_digits=5, verbose_name='taux de commission (%)'),
        ),
    ]
