# Generated by Django 4.2.30 on 2026-08-12 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_commission_negotiated_event_commission_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scanner_agents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'scanner'}, related_name='assigned_events', to=settings.AUTH_USER_MODEL, verbose_name='agents scanner assignés'),
        ),
    ]
