# Generated by Django 4.2.30 on 2026-09-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_scanner_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='valid_date',
            field=models.DateField(blank=True, help_text="Si l'événement dure plusieurs jours et que ce ticket ne donne accès qu'à un jour précis (ex: samedi), indiquez-le ici. Laisser vide si le ticket est valable sur toute la durée de l'événement.", null=True, verbose_name='jour de validité'),
        ),
    ]
