# Generated by Django 4.2.30 on 2026-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventfaq_eventgalleryitem_eventpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgalleryitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name="ordre d'affichage"),
        ),
    ]
