# Generated by Django 4.2.30 on 2026-09-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventgalleryitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(help_text='Information courte affichée sur les cartes et aperçus (max 150 caractères)', max_length=150, verbose_name='InfoLine'),
        ),
    ]
