# Generated by Django 4.2.30 on 2026-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(help_text="Numéro de contact de l'organisateur", max_length=150, verbose_name='InfoLine'),
        ),
    ]
