# Generated by Django 4.2.30 on 2026-09-25 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_free',
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Minimum 100 FCFA', max_digits=10, validators=[django.core.validators.MinValueValidator(100)], verbose_name='prix (FCFA)'),
        ),
    ]
