# Generated by Django 4.2.30 on 2026-09-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_is_free_alter_tickettype_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_message',
            field=models.TextField(blank=True, help_text="Message optionnel ajouté dans l'email de confirmation d'achat de billets. Ex: « Merci d'avoir acheté ! Rendez-vous bientôt 🌟 ». Texte simple uniquement (pas de HTML), 500 caractères max.", max_length=500, verbose_name='message personnalisé'),
        ),
    ]
