# Generated by Django 4.2.30 on 2026-09-30 09:28

import apps.store.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_custom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_file',
            field=models.FileField(blank=True, help_text='Fichier vidéo mp4, 100 Mo maximum. OU renseignez un lien YouTube/Vimeo ci-dessus.', null=True, upload_to='events/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp4']), apps.store.validators.FileSizeValidator(100)], verbose_name='fichier vidéo (mp4)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou Vimeo. OU uploadez un fichier mp4 ci-dessous. Si les deux sont renseignés, le fichier uploadé est prioritaire.', verbose_name='URL vidéo (YouTube/Vimeo)'),
        ),
    ]
