# Generated by Django 4.2.30 on 2026-09-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_video_file_alter_event_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='free_tickets_generated',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Compteur interne — mis à jour à chaque génération.', verbose_name='codes gratuits générés'),
        ),
        migrations.AddField(
            model_name='event',
            name='free_tickets_quota',
            field=models.PositiveIntegerField(default=20, help_text="Nombre maximum de codes gratuits que l'organisateur peut générer pour cet événement. Au-delà, une validation admin est nécessaire.", verbose_name='quota billets gratuits'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='billets vendus'),
        ),
    ]
