# Generated by Django 4.2.30 on 2026-09-30 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_free_tickets_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Jour concerné par ce créneau.', verbose_name='date')),
                ('name', models.CharField(blank=True, help_text="Optionnel. Ex : « Soirée d'ouverture », « Finale ». Si vide, la date sera utilisée comme nom.", max_length=100, verbose_name='nom du jour')),
                ('doors_open', models.TimeField(blank=True, help_text="Heure d'ouverture des portes (optionnel).", null=True, verbose_name='ouverture des portes')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre croissant. Les jours s'affichent dans cet ordre.", verbose_name="ordre d'affichage")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_days', to='events.event', verbose_name='événement')),
            ],
            options={
                'verbose_name': "jour d'événement",
                'verbose_name_plural': "jours d'événement",
                'ordering': ['order', 'date'],
            },
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event_days',
            field=models.ManyToManyField(blank=True, help_text='Laisser vide pour un billet classique (1 scan définitif). Sélectionner 1 jour = billet 1 jour. Sélectionner N jours = pass multi-jours (1 scan par jour).', related_name='ticket_types', to='events.eventday', verbose_name='jours couverts'),
        ),
        migrations.AddConstraint(
            model_name='eventday',
            constraint=models.UniqueConstraint(fields=('event', 'date'), name='unique_event_day_per_date'),
        ),
    ]
