# Generated by Django 4.2.30 on 2026-09-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventday_tickettype_event_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_multi_day',
            field=models.BooleanField(default=False, help_text="Coché automatiquement quand l'événement est créé via le tunnel multi-jours. Active la validation 1 scan par jour.", verbose_name='événement multi-jours'),
        ),
    ]
