# Generated by Django 4.2.30 on 2026-10-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_is_multi_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name="ordre d'affichage"),
        ),
    ]
