# Generated by Django 4.2.30 on 2026-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_tickettype_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='free_tickets_quota',
            field=models.PositiveIntegerField(default=10, help_text="Nombre maximum de codes gratuits que l'organisateur peut générer pour cet événement. Au-delà, une validation admin est nécessaire.", verbose_name='quota billets gratuits'),
        ),
    ]
