# Generated by Django 4.2.16 on 2026-06-24 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_available', models.DecimalField(decimal_places=0, default=0, help_text='Montant disponible pour reversement', max_digits=14, verbose_name='solde disponible')),
                ('balance_pending', models.DecimalField(decimal_places=0, default=0, help_text='Montant en attente de confirmation (délai sécurité 48h)', max_digits=14, verbose_name='solde en attente')),
                ('balance_withdrawn', models.DecimalField(decimal_places=0, default=0, help_text='Total cumulé des reversements effectués', max_digits=14, verbose_name='total reversé')),
                ('preferred_payout_method', models.CharField(choices=[('wave', 'Wave CI'), ('orange_money', 'Orange Money CI'), ('mtn_momo', 'MTN MoMo CI'), ('moov', 'Moov Money')], default='wave', max_length=20, verbose_name='méthode de reversement préférée')),
                ('payout_phone', models.CharField(blank=True, help_text='Numéro pour recevoir les reversements', max_length=20, verbose_name='numéro Mobile Money')),
                ('payout_name', models.CharField(blank=True, help_text='Nom enregistré sur le compte Mobile Money', max_length=200, verbose_name='nom du bénéficiaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.OneToOneField(limit_choices_to={'role': 'organizer'}, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='organisateur')),
            ],
            options={
                'verbose_name': 'wallet organisateur',
                'verbose_name_plural': 'wallets organisateurs',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True, verbose_name='référence')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='montant demandé')),
                ('fee', models.DecimalField(decimal_places=0, default=0, help_text='Frais éventuels déduits du reversement', max_digits=10, verbose_name='frais de traitement')),
                ('amount_net', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='montant net reversé')),
                ('payout_method', models.CharField(choices=[('wave', 'Wave CI'), ('orange_money', 'Orange Money CI'), ('mtn_momo', 'MTN MoMo CI'), ('moov', 'Moov Money')], max_length=20, verbose_name='méthode')),
                ('payout_phone', models.CharField(max_length=20, verbose_name='numéro Mobile Money')),
                ('payout_name', models.CharField(max_length=200, verbose_name='nom bénéficiaire')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('processed', 'Traitée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='statut')),
                ('admin_note', models.TextField(blank=True, help_text="Commentaire de l'administrateur", verbose_name='note admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='dashboard.organizerwallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'demande de reversement',
                'verbose_name_plural': 'demandes de reversement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Crédit (vente)'), ('debit', 'Débit (reversement)'), ('adjustment', 'Ajustement manuel'), ('refund', 'Remboursement')], max_length=20, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='montant')),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='solde après')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('reference', models.CharField(blank=True, help_text='Numéro de commande ou de reversement associé', max_length=200, verbose_name='référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='dashboard.organizerwallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'transaction wallet',
                'verbose_name_plural': 'transactions wallet',
                'ordering': ['-created_at'],
            },
        ),
    ]
