# Generated by Django 4.2.16 on 2026-07-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_withdrawalrequest_dashboard_w_wallet__31bf7c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReversalOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='code OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('withdrawal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='dashboard.withdrawalrequest', verbose_name='demande de reversement')),
            ],
            options={
                'verbose_name': 'OTP reversement',
                'verbose_name_plural': 'OTP reversements',
            },
        ),
    ]
