# Generated by Django 4.2.16 on 2026-07-07 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_reversalotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('publish', 'Publication'), ('unpublish', 'Dépublier'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('payout', 'Reversement'), ('export', 'Export données'), ('scan', 'Scan QR'), ('other', 'Autre')], max_length=20, verbose_name='action')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='modèle')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID objet')),
                ('description', models.TextField(verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_a_user_id_df6777_idx'), models.Index(fields=['action'], name='dashboard_a_action_70e598_idx'), models.Index(fields=['-created_at'], name='dashboard_a_created_818b51_idx')],
            },
        ),
    ]
