# Generated by Django 4.2.16 on 2026-07-07 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True, verbose_name='référence')),
                ('type', models.CharField(choices=[('refund', 'Remboursement'), ('non_delivery', 'Non-livraison'), ('qr_issue', 'Problème QR code'), ('wrong_item', 'Mauvais produit'), ('other', 'Autre')], max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('investigating', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé'), ('rejected', 'Rejeté')], default='open', max_length=20, verbose_name='statut')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email contact')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('order_number', models.CharField(blank=True, max_length=30, verbose_name='numéro de commande')),
                ('ticket_number', models.CharField(blank=True, max_length=30, verbose_name='numéro de ticket')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('description', models.TextField(verbose_name='description')),
                ('resolution', models.TextField(blank=True, verbose_name='résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to=settings.AUTH_USER_MODEL, verbose_name='signalé par')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL, verbose_name='résolu par')),
            ],
            options={
                'verbose_name': 'litige',
                'verbose_name_plural': 'litiges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='dashboard_d_status_64620d_idx'), models.Index(fields=['type'], name='dashboard_d_type_54473c_idx'), models.Index(fields=['reference'], name='dashboard_d_referen_1338d4_idx')],
            },
        ),
    ]
