# Generated by Django 4.2.16 on 2026-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='reversalotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='tentatives'),
        ),
    ]
