# Generated by Django 4.2.30 on 2026-09-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_automatic_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('publish', 'Publication'), ('unpublish', 'Dépublier'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('payout', 'Reversement'), ('payout_requested', 'Demande de reversement créée'), ('payout_otp_validated', 'OTP reversement validé'), ('payout_initiated', 'Reversement initié'), ('payout_provider_pending', 'Reversement provider en attente'), ('payout_success', 'Reversement réussi'), ('payout_failed', 'Reversement échoué'), ('payout_retry', 'Retry reversement'), ('payout_cancelled', 'Reversement annulé'), ('export', 'Export données'), ('scan', 'Scan QR'), ('order_created', 'Commande créée'), ('order_cancelled', 'Commande annulée'), ('order_refunded', 'Commande remboursée'), ('payment_initiated', 'Paiement initié'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('payment_cancelled', 'Paiement annulé'), ('ticket_created', 'Billet(s) généré(s)'), ('ticket_scanned', 'Billet scanné'), ('email_sent', 'Email envoyé'), ('email_failed', 'Email échoué'), ('other', 'Autre')], max_length=30, verbose_name='action'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'credit'), models.Q(('reference', ''), _negated=True)), fields=('wallet', 'reference'), name='wallettransaction_unique_credit_per_wallet_reference'),
        ),
    ]
