# Generated by Django 4.2.30 on 2026-09-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auditlog_reconciliation_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('publish', 'Publication'), ('unpublish', 'Dépublier'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('payout', 'Reversement'), ('payout_requested', 'Demande de reversement créée'), ('payout_otp_validated', 'OTP reversement validé'), ('payout_initiated', 'Reversement initié'), ('payout_provider_pending', 'Reversement provider en attente'), ('payout_success', 'Reversement réussi'), ('payout_failed', 'Reversement échoué'), ('payout_retry', 'Retry reversement'), ('payout_cancelled', 'Reversement annulé'), ('export', 'Export données'), ('scan', 'Scan QR'), ('order_created', 'Commande créée'), ('order_cancelled', 'Commande annulée'), ('order_stock_released', 'Stock libéré (commande expirée)'), ('order_refunded', 'Commande remboursée'), ('payment_initiated', 'Paiement initié'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('payment_cancelled', 'Paiement annulé'), ('payment_paid_stock_unavailable', 'Payé mais stock indisponible'), ('ticket_created', 'Billet(s) généré(s)'), ('ticket_scanned', 'Billet scanné'), ('email_sent', 'Email envoyé'), ('email_failed', 'Email échoué'), ('reconciliation_recovered', 'Paiement récupéré par réconciliation'), ('reconciliation_anomaly', 'Anomalie détectée en réconciliation'), ('other', 'Autre')], max_length=30, verbose_name='action'),
        ),
    ]
