# Generated by Django 4.2.30 on 2026-09-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerwallet',
            name='frozen_reason',
            field=models.TextField(blank=True, help_text='Détail textuel affiché aux admins (titre événement, date, nombre de commandes impactées).', verbose_name='raison du gel'),
        ),
        migrations.AddField(
            model_name='organizerwallet',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text="Wallet gelé — aucune demande de reversement acceptée. Se déclenche automatiquement lors d'une annulation d'événement avec tickets vendus.", verbose_name='gelé'),
        ),
    ]
