# Generated by Django 4.2.30 on 2026-09-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_wallet_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('publish', 'Publication'), ('unpublish', 'Dépublier'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('payout', 'Reversement'), ('payout_requested', 'Demande de reversement créée'), ('payout_otp_validated', 'OTP reversement validé'), ('payout_initiated', 'Reversement initié'), ('payout_provider_pending', 'Reversement provider en attente'), ('payout_success', 'Reversement réussi'), ('payout_failed', 'Reversement échoué'), ('payout_retry', 'Retry reversement'), ('payout_cancelled', 'Reversement annulé'), ('export', 'Export données'), ('scan', 'Scan QR'), ('online_access', 'Accès événement en ligne'), ('order_created', 'Commande créée'), ('order_cancelled', 'Commande annulée'), ('order_stock_released', 'Stock libéré (commande expirée)'), ('order_refunded', 'Commande remboursée'), ('payment_initiated', 'Paiement initié'), ('payment_success', 'Paiement réussi'), ('payment_failed', 'Paiement échoué'), ('payment_cancelled', 'Paiement annulé'), ('payment_paid_stock_unavailable', 'Payé mais stock indisponible'), ('ticket_created', 'Billet(s) généré(s)'), ('ticket_scanned', 'Billet scanné'), ('free_tickets_generated', 'Codes gratuits générés'), ('free_ticket_claimed', 'Billet gratuit réclamé'), ('free_tickets_quota_changed', 'Quota codes gratuits modifié'), ('wallet_unfrozen', 'Wallet dégelé'), ('email_sent', 'Email envoyé'), ('email_failed', 'Email échoué'), ('reconciliation_recovered', 'Paiement récupéré par réconciliation'), ('reconciliation_anomaly', 'Anomalie détectée en réconciliation'), ('other', 'Autre')], max_length=30, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='organizerwallet',
            name='balance_events_available',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Disponible pour reversement (ventes de billets)', max_digits=14, verbose_name='solde événements disponible'),
        ),
        migrations.AlterField(
            model_name='organizerwallet',
            name='balance_events_pending',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Réservé pour un reversement en cours (billetterie)', max_digits=14, verbose_name='solde événements en attente'),
        ),
        migrations.AlterField(
            model_name='organizerwallet',
            name='balance_store_available',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Disponible pour reversement (ventes boutique)', max_digits=14, verbose_name='solde boutique disponible'),
        ),
        migrations.AlterField(
            model_name='organizerwallet',
            name='balance_store_pending',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Réservé pour un reversement en cours (boutique)', max_digits=14, verbose_name='solde boutique en attente'),
        ),
        migrations.AlterField(
            model_name='organizerwallet',
            name='balance_withdrawn',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total cumulé des reversements effectués (événements + boutique)', max_digits=14, verbose_name='total reversé'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('events', 'Événements'), ('store', 'Boutique'), ('legacy', 'Legacy (avant Vague 3.1)')], db_index=True, default='legacy', help_text='Origine du mouvement (billetterie / boutique / pré-refonte).', max_length=20, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='source',
            field=models.CharField(choices=[('events', 'Événements'), ('store', 'Boutique')], default='events', help_text='Portefeuille utilisé pour ce reversement.', max_length=20, verbose_name='source du reversement'),
        ),
    ]
