# Generated by Django 4.2.16 on 2026-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '000_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordonnée GPS automatique', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordonnée GPS automatique', max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
