# Generated by Django 4.2.16 on 2026-07-07 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_useraddress_latitude_useraddress_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kyc_business_doc',
            field=models.FileField(blank=True, help_text="RCCM, attestation fiscale, ou déclaration d'activité", null=True, upload_to='kyc/business/%Y/%m/', verbose_name='document professionnel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_identity_doc',
            field=models.FileField(blank=True, help_text="Carte d'identité, passeport ou carte consulaire", null=True, upload_to='kyc/identity/%Y/%m/', verbose_name="pièce d'identité"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_notes',
            field=models.TextField(blank=True, help_text="Notes internes de l'admin sur la vérification KYC", verbose_name='notes KYC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_proof_of_address',
            field=models.FileField(blank=True, help_text='Facture électricité, eau, ou attestation de domicile', null=True, upload_to='kyc/address/%Y/%m/', verbose_name='justificatif de domicile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KYC soumis le'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='KYC vérifié le'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verified_users', to=settings.AUTH_USER_MODEL, verbose_name='KYC vérifié par'),
        ),
    ]
