# Generated by Django 4.2.16 on 2026-07-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_kyc_business_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organisateur'), ('scanner', 'Agent Scanner'), ('admin', 'Administrateur')], default='organizer', max_length=20, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line1',
            field=models.CharField(max_length=255, verbose_name='adresse ligne 1'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse ligne 2'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='label',
            field=models.CharField(help_text='Ex: Domicile, Bureau', max_length=100, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zone',
            field=models.CharField(choices=[('abidjan', 'Abidjan'), ('grandes_villes', 'Grandes villes'), ('interieur', 'Intérieur du pays')], default='abidjan', max_length=20, verbose_name='zone de livraison'),
        ),
    ]
