# Generated by Django 4.2.16 on 2026-07-13 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kyc_identity_doc',
            field=models.FileField(blank=True, help_text='PDF, JPG ou PNG — 5 Mo max', null=True, upload_to='kyc/identity/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name="pièce d'identité"),
        ),
    ]
