# Generated by Django 4.2.16 on 2026-07-14 09:02

import apps.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_kyc_identity_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kyc_business_doc',
            field=models.FileField(blank=True, help_text="RCCM, attestation fiscale, ou déclaration d'activité — PDF, JPG ou PNG, 5 Mo max", null=True, upload_to='kyc/business/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.accounts.models.validate_kyc_file_size], verbose_name='document professionnel'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_identity_doc',
            field=models.FileField(blank=True, help_text='PDF, JPG ou PNG — 5 Mo max', null=True, upload_to='kyc/identity/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.accounts.models.validate_kyc_file_size], verbose_name="pièce d'identité"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='kyc_proof_of_address',
            field=models.FileField(blank=True, help_text='Facture électricité, eau, ou attestation de domicile — PDF, JPG ou PNG, 5 Mo max', null=True, upload_to='kyc/address/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), apps.accounts.models.validate_kyc_file_size], verbose_name='justificatif de domicile'),
        ),
    ]