# Generated by Django 4.2.30 on 2026-09-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_kyc_business_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organisateur'), ('scanner', 'Agent Scanner'), ('admin', 'Administrateur'), ('finance', 'Finance'), ('support', 'Support'), ('auditor', 'Auditeur (lecture seule)')], default='organizer', max_length=20, verbose_name='rôle'),
        ),
    ]
