# Generated by Django 4.2.30 on 2026-09-18 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_finance_support_auditor_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text="Pour un agent scanner : l'organisateur qui a créé ce compte et à qui il appartient. Détermine qui peut l'assigner à ses événements — évite qu'un organisateur voie ou assigne les agents créés pour un autre organisateur.", limit_choices_to={'role': 'organizer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_agents', to=settings.AUTH_USER_MODEL, verbose_name='géré par (organisateur)'),
        ),
    ]
