# Generated by Django 4.2.16 on 2026-06-22 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Identifiant principal de connexion', max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='nom de famille')),
                ('phone_number', models.CharField(blank=True, help_text='Format international : +225 07 XX XX XX XX', max_length=20, null=True, verbose_name='numéro de téléphone')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('organizer', 'Organisateur'), ('scanner', 'Agent Scanner'), ('admin', 'Administrateur')], default='participant', max_length=20, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour bannir un utilisateur sans supprimer son compte.', verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='photo de profil')),
                ('bio', models.TextField(blank=True, help_text='Utilisé pour les profils organisateurs', verbose_name='biographie')),
                ('is_organizer_verified', models.BooleanField(default=False, help_text="True quand l'admin a validé les documents KYC de l'organisateur", verbose_name='organisateur vérifié')),
                ('organization_name', models.CharField(blank=True, help_text="Nom de l'entreprise ou structure organisatrice", max_length=200, verbose_name="nom de l'organisation")),
                ('organization_description', models.TextField(blank=True, verbose_name="description de l'organisation")),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/', verbose_name="logo de l'organisation")),
                ('organization_website', models.URLField(blank=True, verbose_name='site web')),
                ('city', models.CharField(blank=True, default='Abidjan', max_length=100, verbose_name='ville')),
                ('preferred_language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5, verbose_name='langue préférée')),
                ('notify_email', models.BooleanField(default=True, verbose_name='notifications email')),
                ('notify_sms', models.BooleanField(default=False, verbose_name='notifications SMS')),
                ('notify_push', models.BooleanField(default=True, verbose_name='notifications push')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='dernière connexion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Domicile, Bureau, Maison familiale', max_length=100, verbose_name='libellé')),
                ('full_name', models.CharField(max_length=200, verbose_name='nom complet du destinataire')),
                ('phone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('address_line1', models.CharField(help_text='Numéro et nom de rue, quartier', max_length=255, verbose_name='adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, help_text="Complément d'adresse, bâtiment, appartement", max_length=255, verbose_name='adresse ligne 2')),
                ('city', models.CharField(default='Abidjan', max_length=100, verbose_name='ville')),
                ('zone', models.CharField(choices=[('abidjan', 'Abidjan'), ('grandes_villes', 'Grandes villes (Bouaké, Daloa, Yamoussoukro...)'), ('interieur', 'Intérieur du pays')], default='abidjan', max_length=20, verbose_name='zone de livraison')),
                ('is_default', models.BooleanField(default=False, verbose_name='adresse par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'adresse',
                'verbose_name_plural': 'adresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_number'], name='accounts_cu_phone_n_908ea4_idx'),
        ),
    ]
