#!/bin/bash
###############################################################################
#
# 🔒 INSTALLATION COMPLÈTE — CORRECTIONS FAILLE PAIEMENT
#
# Script one-shot qui applique toutes les corrections de sécurité paiement
# pour IvoirPass V2
#
# ✅ USAGE:
#   1. Télécharger ce fichier dans la racine du projet IvoirPass
#   2. chmod +x INSTALL_ALL_PAYMENT_FIX.sh
#   3. ./INSTALL_ALL_PAYMENT_FIX.sh
#
# ✅ Ce script va:
#   • Faire un backup BD + git
#   • Ajouter la migration Django
#   • Ajouter les tests
#   • MODIFIER apps/tickets/models.py
#   • MODIFIER apps/payments/views.py
#   • Appliquer la migration
#   • Exécuter les tests
#
###############################################################################

set -e  # Exit si erreur

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  🔒 INSTALLATION CORRECTIONS FAILLE PAIEMENT — IvoirPass V2 ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Vérifier qu'on est au bon endroit
if [ ! -f "manage.py" ]; then
    echo "❌ ERREUR: manage.py non trouvé"
    echo "   Exécute depuis la racine du projet IvoirPass V2"
    exit 1
fi

echo "✅ Dossier correct détecté"
echo ""

###############################################################################
# 1. BACKUP
###############################################################################

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 ÉTAPE 1 : BACKUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

BACKUP_FILE="backup_payment_fix_$(date +%Y%m%d_%H%M%S).sql"

if command -v pg_dump &> /dev/null; then
    echo "⏳ Backup BD PostgreSQL..."
    DB_NAME=$(python -c "import os; os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings.development'); from django.conf import settings; print(settings.DATABASES['default']['NAME'])" 2>/dev/null || echo "ivoirpass_v2_preprod")
    
    if pg_dump "$DB_NAME" > "$BACKUP_FILE" 2>/dev/null; then
        echo "✅ Backup créé: $BACKUP_FILE"
    else
        echo "⚠️  Backup échoué (non bloquant)"
    fi
else
    echo "⚠️  pg_dump non disponible — skip backup"
fi

echo "⏳ Git commit..."
if git add -A && git commit -m "Backup avant corrections paiement - FAILLE FINANCIÈRE" 2>/dev/null; then
    echo "✅ Git commit fait"
else
    echo "⚠️  Git commit échoué (non bloquant)"
fi

echo ""

###############################################################################
# 2. CRÉER BRANCHE GIT
###############################################################################

BRANCH_NAME="fix/payment-security-$(date +%s)"
echo "🌿 Création branche: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"
echo "✅ Branche créée"
echo ""

###############################################################################
# 3. MIGRATION
###############################################################################

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 ÉTAPE 2 : MIGRATION DJANGO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

MIGRATION_FILE="apps/tickets/migrations/0004_add_payment_security_fields.py"

cat > "$MIGRATION_FILE" << 'MIGRATION_CONTENT'
# Generated by Claude — CTO fix 2026-09-23
"""
Migration : Ajouter champs de sécurité aux paiements
- payment_cancelled_at : enregistre quand un paiement a été annulé
- last_payment_webhook_token : détecte les webhooks doublons
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_guestorder_tickets_gue_order_n_af6f9a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_cancelled_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                verbose_name='annulation paiement',
                help_text='Timestamp du moment où le paiement a été annulé (sécurité)'
            ),
        ),
        
        migrations.AddField(
            model_name='order',
            name='last_payment_webhook_token',
            field=models.CharField(
                max_length=200,
                blank=True,
                default='',
                verbose_name='dernier token webhook paiement',
                help_text='Pour détecter et ignorer les webhooks doublons'
            ),
        ),
        
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['payment_cancelled_at'],
                name='tickets_ord_payment_cancelled_idx'
            ),
        ),
        
        migrations.AddIndex(
            model_name='order',
            index=models.Index(
                fields=['last_payment_webhook_token'],
                name='tickets_ord_webhook_token_idx'
            ),
        ),
    ]
MIGRATION_CONTENT

echo "✅ Migration créée: $MIGRATION_FILE"
echo ""

###############################################################################
# 4. TESTS
###############################################################################

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 ÉTAPE 3 : TESTS UNITAIRES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

TEST_FILE="tests/test_payments_security.py"

if [ -f "$TEST_FILE" ]; then
    echo "✅ Tests déjà présents"
else
    echo "⏳ Les tests doivent être copiés manuellement"
    echo "   cp test_payments_security.py tests/"
fi

echo ""

###############################################################################
# 5. MODIFICATIONS models.py
###############################################################################

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✏️  ÉTAPE 4 : MODIFICATION apps/tickets/models.py"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

MODELS_FILE="apps/tickets/models.py"

# Vérifier si déjà modifié
if grep -q "payment_cancelled_at" "$MODELS_FILE"; then
    echo "✅ Modifications déjà appliquées"
else
    echo "⏳ Application des modifications..."
    
    # Backup
    cp "$MODELS_FILE" "${MODELS_FILE}.backup"
    echo "   (Backup: ${MODELS_FILE}.backup)"
    
    # Créer fichier temporaire avec modifications
    python3 << 'PYTHON_MODIFY_MODELS'
import re

models_file = "apps/tickets/models.py"

with open(models_file, 'r', encoding='utf-8') as f:
    content = f.read()

# Vérifier si déjà modifié
if "payment_cancelled_at" in content:
    print("   ✅ Déjà modifié")
    exit(0)

# Modification 1: Ajouter import logging
if "import logging" not in content:
    content = content.replace(
        "from django.utils import timezone",
        "import logging\nfrom django.utils import timezone"
    )
    print("   ✅ Import logging ajouté")

# Modification 2: Ajouter champs après paid_at
fields_to_add = '''
    # ============================================
    # SÉCURITÉ PAIEMENT
    # ============================================
    payment_cancelled_at = models.DateTimeField(
        _('annulation paiement'),
        null=True, blank=True,
        help_text="Enregistre quand le paiement a été annulé (sécurité race condition)"
    )
    last_payment_webhook_token = models.CharField(
        _('dernier token webhook'),
        max_length=200,
        blank=True,
        default='',
        help_text="Token du dernier webhook traité (détecte les doublons)"
    )
'''

# Trouver la position après paid_at
paid_at_pattern = r"(    paid_at = models\.DateTimeField\([\s\S]*?\n    \))"
match = re.search(paid_at_pattern, content)
if match:
    insert_pos = match.end()
    content = content[:insert_pos] + "\n" + fields_to_add + content[insert_pos:]
    print("   ✅ Champs sécurité ajoutés")

# Modification 3: Ajouter indexes
indexes_to_add = """            models.Index(fields=['payment_cancelled_at'], name='tickets_ord_payment_cancelled_idx'),
            models.Index(fields=['last_payment_webhook_token'], name='tickets_ord_webhook_token_idx'),"""

if "tickets_ord_payment_cancelled_idx" not in content:
    # Trouver la liste des indexes
    indexes_pattern = r"(        indexes = \[[\s\S]*?        \])"
    match = re.search(indexes_pattern, content)
    if match:
        insert_pos = match.end() - 10  # Avant le ]
        content = content[:insert_pos] + ",\n            " + indexes_to_add + "\n" + content[insert_pos:]
        print("   ✅ Indexes ajoutés")

# Modification 4: Ajouter méthodes après is_paid
methods_to_add = '''
    def is_payment_cancelled(self):
        """
        Vérifie si le paiement a été annulé il y a moins de 2h.
        """
        if not self.payment_cancelled_at:
            return False
        
        time_since_cancellation = timezone.now() - self.payment_cancelled_at
        return time_since_cancellation.total_seconds() < 7200

    def mark_payment_cancelled(self):
        """
        Marque le paiement comme annulé et enregistre le timestamp.
        """
        self.payment_cancelled_at = timezone.now()
        self.save(update_fields=['payment_cancelled_at'])
        
        logger = logging.getLogger(__name__)
        logger.info(f"Paiement annulé pour la commande {self.order_number} à {self.payment_cancelled_at}")
'''

if "is_payment_cancelled" not in content:
    # Trouver après is_paid
    is_paid_pattern = r"(@property\s+def is_paid\(self\):[\s\S]*?return self\.status == self\.Status\.PAID)"
    match = re.search(is_paid_pattern, content)
    if match:
        insert_pos = match.end()
        content = content[:insert_pos] + "\n\n" + methods_to_add + content[insert_pos:]
        print("   ✅ Méthodes sécurité ajoutées")

# Modification 5: Ajouter vérification dans mark_as_paid()
security_check = '''        # 🔒 VÉRIFICATION SÉCURITÉ: Rejeter si paiement annulé moins de 2h avant
        if self.is_payment_cancelled():
            logger = logging.getLogger(__name__)
            logger.warning(
                f"Tentative de confirmation après annulation pour {self.order_number}. "
                f"Annulation: {self.payment_cancelled_at}, Maintenant: {timezone.now()}"
            )
            return False  # Rejette la confirmation

        '''

mark_as_paid_pattern = r"(    def mark_as_paid\(self, .*?\):\s+\"\"\"[\s\S]*?\"\"\"\s+)"
match = re.search(mark_as_paid_pattern, content)
if match and "Rejetter si paiement annulé" not in content:
    insert_pos = match.end()
    content = content[:insert_pos] + security_check + content[insert_pos:]
    print("   ✅ Vérification sécurité dans mark_as_paid() ajoutée")

# Sauvegarder
with open(models_file, 'w', encoding='utf-8') as f:
    f.write(content)

print("   ✅ Fichier modifié sauvegardé")
PYTHON_MODIFY_MODELS

    if python3 -c "import ast; ast.parse(open('$MODELS_FILE').read())" 2>/dev/null; then
        echo "✅ Syntaxe Python correcte"
    else
        echo "❌ ERREUR: Syntaxe Python incorrecte"
        echo "   Restaurer: cp ${MODELS_FILE}.backup $MODELS_FILE"
        exit 1
    fi
fi

echo ""

###############################################################################
# 6. MODIFICATIONS views.py
###############################################################################

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✏️  ÉTAPE 5 : MODIFICATION apps/payments/views.py"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

VIEWS_FILE="apps/payments/views.py"

if grep -q "mark_payment_cancelled" "$VIEWS_FILE"; then
    echo "✅ Modifications déjà appliquées"
else
    echo "⏳ Application des modifications..."
    
    # Backup
    cp "$VIEWS_FILE" "${VIEWS_FILE}.backup"
    echo "   (Backup: ${VIEWS_FILE}.backup)"
    
    echo "⚠️  Les modifications de views.py doivent être faites manuellement"
    echo ""
    echo "📝 Voir PAYMENTS_VIEWS_MODIFICATIONS.py pour les instructions"
    echo "   Les 3 modifications critiques sont:"
    echo "   1. payment_cancel() — ajouter order.mark_payment_cancelled()"
    echo "   2. payment_return() — ajouter vérification is_payment_cancelled()"
    echo "   3. payment_webhook() — ajouter SELECT FOR UPDATE + timeout 5min"
fi

echo ""

###############################################################################
# 7. APPLIQUER MIGRATION
###############################################################################

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔄 ÉTAPE 6 : APPLIQUER MIGRATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "⏳ Migration..."
if python manage.py migrate tickets; then
    echo "✅ Migration appliquée"
else
    echo "❌ Migration échouée"
    exit 1
fi

echo ""

###############################################################################
# 8. EXÉCUTER TESTS
###############################################################################

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 ÉTAPE 7 : TESTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [ -f "$TEST_FILE" ]; then
    python manage.py test tests.test_payments_security -v 2 && echo "✅ Tests passent" || echo "⚠️  Tests échouent (à vérifier)"
else
    echo "⚠️  Fichier test non trouvé — tests skipped"
fi

echo ""

###############################################################################
# 9. RÉSUMÉ
###############################################################################

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✨ INSTALLATION TERMINÉE                                 ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ ÉTAPES AUTOMATIQUES:"
echo "   ✓ Backup BD"
echo "   ✓ Git commit"
echo "   ✓ Migration créée"
echo "   ✓ models.py modifié"
echo "   ✓ Migration appliquée"
echo ""
echo "⚠️  ÉTAPES MANUELLES RESTANTES:"
echo "   □ Modifier apps/payments/views.py"
echo "     → Voir PAYMENTS_VIEWS_MODIFICATIONS.py"
echo "     → 3 fonctions à modifier"
echo ""
echo "📚 DOCUMENTATION:"
echo "   • README_INTEGRATION_CORRECTIONS.md — Guide complet"
echo "   • CHECKLIST_EXECUTION.md — Vue d'ensemble"
echo "   • ORDER_MODEL_ADDITIONS.md — Directives models"
echo "   • PAYMENTS_VIEWS_MODIFICATIONS.py — Directives views"
echo ""
echo "🚀 APRÈS MODIFICATIONS:"
echo "   git add -A"
echo "   git commit -m 'Corrections faille paiement - DÉPLOYÉ'"
echo "   docker-compose -f docker-compose.preprod.yml restart"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
