# Generated by Django 4.2.16 on 2026-06-24 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '000_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='sous-titre')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='description courte')),
                ('product_type', models.CharField(choices=[('physical', 'Physique (livraison)'), ('digital', 'Numérique (téléchargement)'), ('bundle', 'Bundle (physique + numérique)')], default='physical', max_length=20, verbose_name='type de produit')),
                ('tags', models.CharField(blank=True, max_length=300, verbose_name='tags')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='store/covers/%Y/%m/', verbose_name='image de couverture')),
                ('preview_file', models.FileField(blank=True, help_text='Extrait gratuit (PDF, MP3...)', null=True, upload_to='store/previews/%Y/%m/', verbose_name='fichier aperçu')),
                ('digital_file', models.FileField(blank=True, help_text='Fichier complet — non accessible publiquement', null=True, upload_to='store/digital/%Y/%m/', verbose_name='fichier numérique')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='auteur/artiste')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='éditeur/label')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='année')),
                ('language', models.CharField(blank=True, default='Français', max_length=50, verbose_name='langue')),
                ('pages', models.PositiveIntegerField(blank=True, help_text='Pour les livres', null=True, verbose_name='nombre de pages')),
                ('duration', models.CharField(blank=True, help_text='Pour les albums (ex: 45 min)', max_length=20, verbose_name='durée')),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='prix (FCFA)')),
                ('price_physical', models.DecimalField(blank=True, decimal_places=0, help_text='Pour les bundles : prix partie physique', max_digits=10, null=True, verbose_name='prix version physique')),
                ('price_digital', models.DecimalField(blank=True, decimal_places=0, help_text='Pour les bundles : prix partie numérique', max_digits=10, null=True, verbose_name='prix version numérique')),
                ('stock', models.PositiveIntegerField(default=0, help_text='0 pour produits numériques (illimité)', verbose_name='stock physique')),
                ('sold_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='exemplaires vendus')),
                ('download_limit', models.PositiveIntegerField(default=3, help_text='Nombre max de téléchargements par achat', verbose_name='limite de téléchargements')),
                ('download_expiry_hours', models.PositiveIntegerField(default=48, verbose_name='expiration lien (heures)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('out_stock', 'Rupture de stock'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='bi-bag', help_text='Classe Bootstrap Icons', max_length=50, verbose_name='icône')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'catégorie produit',
                'verbose_name_plural': 'catégories produits',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='numéro de commande')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='prix unitaire')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='sous-total')),
                ('commission', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='commission IvoirPass')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='total')),
                ('delivery_method', models.CharField(choices=[('download', 'Téléchargement numérique'), ('delivery', 'Livraison physique')], default='download', max_length=20, verbose_name='méthode de livraison')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='numéro de suivi')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='statut')),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to=settings.AUTH_USER_MODEL, verbose_name='acheteur')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.useraddress', verbose_name='adresse de livraison')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'commande produit',
                'verbose_name_plural': 'commandes produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.productcategory', verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='vendeur'),
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='téléchargements effectués')),
                ('max_downloads', models.PositiveIntegerField(default=3, verbose_name='limite de téléchargements')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='store.productorder', verbose_name='commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='store.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'lien de téléchargement',
                'verbose_name_plural': 'liens de téléchargement',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_361302_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'product_type'], name='store_produ_status_cd2f63_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'status'], name='store_produ_seller__6cca5d_idx'),
        ),
    ]
