# Generated by Django 4.2.16 on 2026-06-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_negotiated',
            field=models.BooleanField(default=False, verbose_name='commission négociée'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Commission IvoirPass prélevée sur le vendeur', max_digits=5, verbose_name='taux de commission (%)'),
        ),
    ]
