# Generated by Django 4.2.16 on 2026-07-05 12:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_old_delivery_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='numéro de commande')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='prix unitaire')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='sous-total')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='total')),
                ('delivery_method', models.CharField(choices=[('download', 'Téléchargement'), ('delivery', 'Livraison')], default='download', max_length=20, verbose_name='méthode de livraison')),
                ('delivery_name', models.CharField(blank=True, max_length=200, verbose_name='nom destinataire')),
                ('delivery_phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('delivery_address', models.TextField(blank=True, verbose_name='adresse complète')),
                ('delivery_city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('delivery_commune', models.CharField(blank=True, max_length=100, verbose_name='commune')),
                ('delivery_country', models.CharField(blank=True, default="Côte d'Ivoire", max_length=100, verbose_name='pays')),
                ('delivery_instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='numéro de suivi')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='statut')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='méthode de paiement')),
                ('payment_reference', models.CharField(blank=True, max_length=200, verbose_name='référence de paiement')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='expédié le')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='livré le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_orders', to='store.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'commande boutique invité',
                'verbose_name_plural': 'commandes boutique invités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestDownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='téléchargements effectués')),
                ('max_downloads', models.PositiveIntegerField(default=3, verbose_name='limite de téléchargements')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='store.guestproductorder', verbose_name='commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_download_links', to='store.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'lien téléchargement invité',
                'verbose_name_plural': 'liens téléchargement invités',
            },
        ),
        migrations.AddIndex(
            model_name='guestproductorder',
            index=models.Index(fields=['email', 'status'], name='store_guest_email_50ced5_idx'),
        ),
        migrations.AddIndex(
            model_name='guestproductorder',
            index=models.Index(fields=['product', 'status'], name='store_guest_product_634dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='guestproductorder',
            index=models.Index(fields=['order_number'], name='store_guest_order_n_b66acf_idx'),
        ),
    ]
