# Generated by Django 4.2.16 on 2026-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_guestproductorder_guestdownloadlink_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='downloadlink',
            index=models.Index(fields=['token'], name='store_downl_token_d2d8f0_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadlink',
            index=models.Index(fields=['expires_at'], name='store_downl_expires_b647c4_idx'),
        ),
        migrations.AddIndex(
            model_name='guestdownloadlink',
            index=models.Index(fields=['token'], name='store_guest_token_825bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='guestdownloadlink',
            index=models.Index(fields=['expires_at'], name='store_guest_expires_13fc0d_idx'),
        ),
        migrations.AddIndex(
            model_name='guestproductorder',
            index=models.Index(fields=['status'], name='store_guest_status_ab2c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='guestproductorder',
            index=models.Index(fields=['-created_at'], name='store_guest_created_869cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['buyer', 'status'], name='store_produ_buyer_i_489d82_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['product', 'status'], name='store_produ_product_ddc358_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['order_number'], name='store_produ_order_n_07eb18_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['status'], name='store_produ_status_f52627_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['-created_at'], name='store_produ_created_9b1ebe_idx'),
        ),
    ]
