# Generated by Django 4.2.16 on 2026-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_downloadlink_store_downl_token_d2d8f0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestproductorder',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude livraison'),
        ),
        migrations.AddField(
            model_name='guestproductorder',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude livraison'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude livraison'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude livraison'),
        ),
    ]
