# Generated by Django 4.2.30 on 2026-09-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_guestproductorder_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestproductorder',
            name='delivery_method',
            field=models.CharField(choices=[('download', 'Téléchargement'), ('delivery', 'Livraison'), ('both', 'Bundle (physique + numérique)')], default='download', max_length=20, verbose_name='méthode de livraison'),
        ),
    ]
