# Generated by Django 4.2.30 on 2026-09-27 00:06

import apps.store.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_standardize_download_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/covers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.webp']), apps.store.validators.FileSizeValidator(5)], verbose_name='image de couverture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Fichier complet — non accessible publiquement', null=True, upload_to='store/digital/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['.mp3', '.wav', '.flac', '.m4a', '.aac', '.ogg', '.mp4', '.mov', '.webm', '.pdf', '.epub', '.jpg', '.jpeg', '.png', '.webp', '.zip']), apps.store.validators.validate_digital_file_type], verbose_name='fichier numérique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_file',
            field=models.FileField(blank=True, help_text='Extrait gratuit (PDF, MP3...)', null=True, upload_to='store/previews/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['.pdf', '.mp3', '.jpg', '.jpeg', '.png']), apps.store.validators.FileSizeValidator(20)], verbose_name='fichier aperçu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(500)], verbose_name='prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_digital',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Pour les bundles : prix partie numérique', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(500)], verbose_name='prix version numérique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_physical',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Pour les bundles : prix partie physique', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(500)], verbose_name='prix version physique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, help_text='Numéro de contact du propriétaire', max_length=500, verbose_name='InfoLine'),
        ),
    ]
