# Generated by Django 4.2.30 on 2026-09-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_cover_image_alter_product_digital_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestdownloadlink',
            name='external_click_count',
            field=models.PositiveIntegerField(default=0, help_text='Compteur informatif des clics vers product.external_url. Ne consomme PAS la limite de téléchargements.', verbose_name='clics vers lien externe'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, help_text="Spotify, Apple Music, Deezer, Bandcamp... Remplis ce champ OU uploade un fichier numérique. Si les deux sont renseignés, l'URL externe est servie en priorité (pour compter les clics).", max_length=500, verbose_name='lien externe (album/streaming)'),
        ),
    ]
