# Generated by Django 4.2.30 on 2026-09-27 07:04

import apps.store.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_guestdownloadlink_external_click_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='store/covers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.store.validators.FileSizeValidator(5)], verbose_name='image de couverture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='digital_file',
            field=models.FileField(blank=True, help_text='Fichier complet — non accessible publiquement', null=True, upload_to='store/digital/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'flac', 'm4a', 'aac', 'ogg', 'mp4', 'mov', 'webm', 'pdf', 'epub', 'jpg', 'jpeg', 'png', 'webp', 'zip']), apps.store.validators.validate_digital_file_type], verbose_name='fichier numérique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_file',
            field=models.FileField(blank=True, help_text='Extrait gratuit (PDF, MP3...)', null=True, upload_to='store/previews/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'mp3', 'jpg', 'jpeg', 'png']), apps.store.validators.FileSizeValidator(20)], verbose_name='fichier aperçu'),
        ),
    ]
