# Generated by Django 4.2.16 on 2026-06-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paydunya_token', models.CharField(blank=True, help_text='Token unique de la transaction PayDunya', max_length=200, verbose_name='token PayDunya')),
                ('paydunya_invoice_token', models.CharField(blank=True, max_length=200, verbose_name='token facture')),
                ('provider', models.CharField(choices=[('paydunya', 'PayDunya'), ('wave', 'Wave'), ('orange', 'Orange Money'), ('mtn', 'MTN MoMo'), ('moov', 'Moov Money'), ('djamo', 'Djamo'), ('card', 'Carte Bancaire')], default='paydunya', max_length=20, verbose_name='opérateur')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant')),
                ('currency', models.CharField(default='XOF', max_length=5, verbose_name='devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='statut')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='réponse brute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tickets.order', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['paydunya_token'], name='payments_pa_payduny_3525b4_idx'), models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx')],
            },
        ),
    ]
