# Generated by Django 4.2.30 on 2026-09-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_guestorder_tickets_gue_order_n_af6f9a_idx_and_more'),
        ('payments', '0002_payment_payments_pa_status_7ad4af_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='guest_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tickets.guestorder', verbose_name='commande invité'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tickets.order', verbose_name='commande'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['guest_order', 'status'], name='payments_pa_guest_o_5d20e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('guest_order__isnull', True), ('order__isnull', False)), models.Q(('guest_order__isnull', False), ('order__isnull', True)), _connector='OR'), name='payment_exactly_one_of_order_or_guest_order'),
        ),
    ]
