# Generated by Django 4.2.30 on 2026-09-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_guestproductorder_delivery_latitude_and_more'),
        ('payments', '0003_payment_guest_order_alter_payment_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_exactly_one_of_order_or_guest_order',
        ),
        migrations.AddField(
            model_name='payment',
            name='guest_product_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.guestproductorder', verbose_name='commande boutique invité'),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.productorder', verbose_name='commande boutique'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['product_order', 'status'], name='payments_pa_product_84171c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['guest_product_order', 'status'], name='payments_pa_guest_p_12eec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('guest_order__isnull', True), ('guest_product_order__isnull', True), ('order__isnull', False), ('product_order__isnull', True)), models.Q(('guest_order__isnull', False), ('guest_product_order__isnull', True), ('order__isnull', True), ('product_order__isnull', True)), models.Q(('guest_order__isnull', True), ('guest_product_order__isnull', True), ('order__isnull', True), ('product_order__isnull', False)), models.Q(('guest_order__isnull', True), ('guest_product_order__isnull', False), ('order__isnull', True), ('product_order__isnull', True)), _connector='OR'), name='payment_exactly_one_order_type'),
        ),
    ]
