# Generated by Django 4.2.16 on 2026-06-24 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='numéro de commande')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='sous-total')),
                ('commission', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='commission IvoirPass')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='total payé')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='statut')),
                ('payment_method', models.CharField(blank=True, help_text='wave, orange_money, mtn_momo, card, cinetpay', max_length=50, verbose_name='moyen de paiement')),
                ('payment_reference', models.CharField(blank=True, max_length=200, verbose_name='référence paiement')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='payée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='acheteur')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='prix unitaire')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='sous-total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.order', verbose_name='commande')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='events.tickettype', verbose_name='type de ticket')),
            ],
            options={
                'verbose_name': 'ligne de commande',
                'verbose_name_plural': 'lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticket_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='numéro de ticket')),
                ('qr_code_data', models.CharField(blank=True, help_text='Chaîne signée HMAC encodée dans le QR Code', max_length=500, verbose_name='données QR Code')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/%Y/%m/', verbose_name='image QR Code')),
                ('status', models.CharField(choices=[('valid', 'Valide'), ('used', 'Utilisé'), ('expired', 'Expiré'), ('void', 'Annulé')], default='valid', max_length=20, verbose_name='statut')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='scanné le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.orderitem', verbose_name='ligne de commande')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='scanné par')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_number'], name='tickets_tic_ticket__bf3905_idx'), models.Index(fields=['uuid'], name='tickets_tic_uuid_33f119_idx'), models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='tickets_ord_order_n_7fc1aa_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='tickets_ord_buyer_i_408e96_idx'),
        ),
    ]
