# Generated by Django 4.2.16 on 2026-07-02 14:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_commission_negotiated_event_commission_note_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='numéro de commande')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'commande invité',
                'verbose_name_plural': 'commandes invités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_items', to='tickets.guestorder')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.tickettype')),
            ],
            options={
                'verbose_name': 'ligne de commande invité',
                'verbose_name_plural': 'lignes de commande invités',
            },
        ),
        migrations.CreateModel(
            name='GuestTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ticket_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('qr_code_data', models.CharField(blank=True, max_length=500)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/%Y/%m/')),
                ('status', models.CharField(choices=[('valid', 'Valide'), ('used', 'Utilisé'), ('void', 'Annulé')], default='valid', max_length=20)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.guestorderitem')),
            ],
            options={
                'verbose_name': 'ticket invité',
                'verbose_name_plural': 'tickets invités',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_number'], name='tickets_gue_ticket__46526e_idx'), models.Index(fields=['uuid'], name='tickets_gue_uuid_397a23_idx'), models.Index(fields=['status'], name='tickets_gue_status_b9ab6d_idx')],
            },
        ),
    ]
