# Generated by Django 4.2.16 on 2026-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_guestorder_guestorderitem_guestticket'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guestorder',
            index=models.Index(fields=['order_number'], name='tickets_gue_order_n_af6f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='guestorder',
            index=models.Index(fields=['email', 'status'], name='tickets_gue_email_520b95_idx'),
        ),
        migrations.AddIndex(
            model_name='guestorder',
            index=models.Index(fields=['status'], name='tickets_gue_status_488da2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='tickets_ord_status_44f72e_idx'),
        ),
    ]
