# Generated by Django 4.2.30 on 2026-09-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_guestorder_tickets_gue_order_n_af6f9a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestorder',
            name='last_payment_webhook_token',
            field=models.CharField(blank=True, default='', help_text='Token du dernier webhook traité (détecte les doublons)', max_length=200, verbose_name='dernier token webhook'),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='payment_cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Enregistre quand le paiement a été annulé (sécurité race condition)', null=True, verbose_name='annulation paiement'),
        ),
        migrations.AddIndex(
            model_name='guestorder',
            index=models.Index(fields=['payment_cancelled_at'], name='guestord_pay_cancelled_idx'),
        ),
        migrations.AddIndex(
            model_name='guestorder',
            index=models.Index(fields=['last_payment_webhook_token'], name='guestord_webhook_tok_idx'),
        ),
    ]
