# Generated by Django 4.2.30 on 2026-09-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_guestorder_payment_cancelled_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestticket',
            name='online_access_token',
            field=models.CharField(blank=True, help_text="Jeton unique pour accéder à l'événement en ligne. Rempli uniquement pour les événements online/hybrid.", max_length=64, null=True, unique=True, verbose_name="jeton d'accès en ligne"),
        ),
    ]
