# Generated by Django 4.2.30 on 2026-09-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_free_tickets_generated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_guestorder_access_token_guestticket_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTicketCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Format FREE-XXXX-XXXX (généré automatiquement).', max_length=20, unique=True, verbose_name='code')),
                ('beneficiary_name', models.CharField(max_length=200, verbose_name='nom du bénéficiaire')),
                ('beneficiary_email', models.EmailField(max_length=254, verbose_name='email du bénéficiaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_free_ticket_codes', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_ticket_codes', to='events.event', verbose_name='événement')),
                ('guest_ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_code', to='tickets.guestticket', verbose_name='billet émis')),
                ('ticket_type', models.ForeignKey(blank=True, help_text='Optionnel — laisser vide pour utiliser le premier type.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.tickettype', verbose_name='type de ticket')),
            ],
            options={
                'verbose_name': 'code de billet gratuit',
                'verbose_name_plural': 'codes de billets gratuits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='tickets_fre_code_2549be_idx'), models.Index(fields=['event', 'used_at'], name='tickets_fre_event_i_2705b0_idx')],
            },
        ),
    ]
