# Generated by Django 4.2.30 on 2026-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_freeticketcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestorder',
            name='commission',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Commission prélevée par IvoirPass sur cette commande, figée au moment du paiement pour la traçabilité comptable. N'est PAS utilisée pour créditer le wallet (le signal dashboard/signals.py recalcule à la volée).", max_digits=12, verbose_name='commission IvoirPass'),
        ),
    ]
