# Generated by Django 4.2.16 on 2026-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_event', 'Nouvel événement'), ('new_product', 'Nouveau produit'), ('withdrawal', 'Demande de reversement'), ('fraud_alert', 'Alerte fraude')], max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='référence')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notification admin',
                'verbose_name_plural': 'notifications admin',
                'ordering': ['-created_at'],
            },
        ),
    ]
